### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [OpticksSecurity/gtm-sensor-template#1]
https://github.com/OpticksSecurity/gtm-sensor-template/blob/00d97afc86891c80d665cc375960155783c73183/template.tpl#L108

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by aserrabl** [comment]
Thank you for your insights @semisight , the issue has been resolved in https://github.com/OpticksSecurity/gtm-sensor-template/commit/40b7ba031d977fba2362d937241971b55ae7e295.
